# action name
name: 'build-linux-packages'

# action author
author: 'Kyle Penfound <kpenfound@hashicorp.com>'

# action description
description: 'Packages binaries using nfpm.'

# action input values
inputs:
  name:
    description: 'Product name.'
    default: ''
    required: true
  arch:
    description: 'Build architecture.'
    default: ''
    required: true
  version:
    description: 'Product semver version.'
    default: ''
    required: true
  maintainer:
    description: 'Maintainer name.'
    default: ''
    required: false
  description:
    description: 'Product description.'
    default: ''
    required: false
  homepage:
    description: 'Product homepage.'
    default: ''
    required: false
  license:
    description: 'Product license.'
    default: ''
    required: false
  binary:
    description: 'Binary location to package.'
    default: ''
    required: true
  config_dir:
    description: 'Directory of configs in desired filesystem structure.'
    default: ''
    required: false
  deb_depends:
    description: 'Comma separated list of deb dependencies.'
    default: ''
    required: false
  rpm_depends:
    description: 'Comma separated list of rpm dependencies.'
    default: ''
    required: false
  preinstall:
    description: 'Preinstall script location.'
    default: ''
    required: false
  postinstall:
    description: 'Postinstall script location.'
    default: ''
    required: false
  preremove:
    description: 'Preremove script location.'
    default: ''
    required: false
  postremove:
    description: 'Postremove script location.'
    default: ''
    required: false

# action runner (golang:latest image)
runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build nfpm_template
        shell: bash
        env:
          INPUT_NAME: ${{ inputs.name }}
          INPUT_ARCH:  ${{ inputs.arch }}
          INPUT_VERSION:  ${{ inputs.version }}
          INPUT_MAINTAINER:  ${{ inputs.maintainer }}
          INPUT_DESCRIPTION: ${{ inputs.description }}
          INPUT_HOMEPAGE: ${{ inputs.homepage }}
          INPUT_LICENSE: ${{ inputs.license }}
#          INPUT_DEPENDS:
          INPUT_BINARY: ${{ inputs.binary }}
          INPUT_CONFIG_DIR: ${{ inputs.config_dir }}
          INPUT_PREINSTALL: ${{ inputs.preinstall }}
          INPUT_POSTINSTALL: ${{ inputs.postinstall }}
          INPUT_PREREMOVE: ${{ inputs.preremove }}
          INPUT_POSTREMOVE: ${{ inputs.postremove }}

        run: |
          go mod download
          go build -o nfpm_template

    - run |
      echo "Creating template files..."
      INPUT_DEPENDS=$INPUT_RPM_DEPENDS /usr/local/bin/nfpm_template > ./nfpm_rpm_config.yaml
      INPUT_DEPENDS=$INPUT_DEB_DEPENDS /usr/local/bin/nfpm_template > ./nfpm_deb_config.yaml

      echo "Packaging..."
      /usr/local/bin/nfpm package -f ./nfpm_rpm_config.yaml -p rpm -t ./out/
      /usr/local/bin/nfpm package -f ./nfpm_deb_config.yaml -p deb -t ./out/
      shell: bash
  - name: Upload Tarball
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.TARBALL_NAME}}
        path: ${{env.TARBALL_NAME}}
#  using: 'docker'
#  image: 'Dockerfile'
#  env:
#    GO111MODULE: 'on'

